---
title: A Condorect-Hare Manifesto
author: Joseph T. Ornstein
date: '2020-07-31'
slug: cordorcet-hare-manifesto
categories: 
- Political Science
tags: []
images: []
draft: true
---

If you're familiar with any non-plurality social choice rule, it's probably [Ranked Choice Voting](), aka Instant Runoff Voting (IRV) or -- across the pond -- as Single Transferable Vote (STV). Under RCV/IRV/STV, voters submit a preference *ranking* and the candidate with the fewest first-place votes is eliminated until one candidate has an outright majority of first-place votes. 

To its credit, RCV/IRV/STV gets a lot right. It is straightforward to understand. At least, straightforward compared to some of its

But RCV also has serious - in my mind, disqualifying - flaws. Chief among them, nonmonotonicity. Increasing support for a candidate can, under some circumstance, cause that candidate to lose. And conversely, decreasing support for a candidate can cause that candidate to win! In [paper](), Bob Norman and I show that there are two (necessary and sufficient) conditions under which such a paradox will occur with three candidates.

1. RCV fails to select the Condorcet winner.

2. The election is a competitive three-way race. Each candidate receives at least 25% of the first-place vote.^[To see the intuition, label the candidates A, B, and C. Candidate A is the RCV winner, and Candidate C is the Condorcet winner. The only way that RCV could fail to select the Condorcet winner is if C is *eliminated* during the first round. So long as each candidate has at least 25% of the first-place vote, shifting support from B to A will cause B to be eliminated before A receives a majority of first-place votes. Once B is eliminated, C wins (she must win a two way race with A; she's the Condorcet candidate).]

How often should we expect this to happen? Basically, whenever there's a competitive multi-candidate race and one candidate is the "consensus" pick between two extremes. For example, in a tight election between a left-wing, moderate, and right-wing candidate, the moderate may be preferred in all pairwise comparisons -- right-wing + moderate voters prefer her over the left-wing candidate, and left-wing + moderate voters prefer her over the right-wing candidate -- but she receives the least first-place support. It's precisely in this situation where, paradoxically, increasing the support of one of the extremist candidates would cause him to lose. 

What a damning finding! The very outcome that alternative voting systems are designed to foster -- competitive multiparty elections -- is precisely when the system starts to unravel!

But as Nicolaus Tideman pointed out a few years back, these two conditions actually point to an elegant solution. Why not just adopt **Condorcet-Hare**?

Ordinary RCV has one nice advantage: it is straightforward to explain:

> Rank the candidates in order from your most to least preferred. If one candidate receives a majority of first-place votes, they will be elected. Otherwise, the candidate with the fewest first-place votes will be eliminated until one candidate receives a majority.

But Condorcet-Hare is not any more difficult to explain. Observe the difference:

> Rank the candidates in order from your most to least preferred. If one candidate is *preferred by a majority of voters to any other candidate*, they will be elected. Otherwise, the candidate with the fewest first-place votes will be eliminated until *there is a majority choice*. 

There. Doesn't seem harder to understand than vanilla RCV. 

Another nice feature of Condorcet-Hare is that the full preference of B voters aren't ignored.  

Where Condorcet-Hare falls short compared to Vanilla RCV is on the ["Later No Harm" criterion](https://en.wikipedia.org/wiki/Later-no-harm_criterion). Extremist voters may "bullet vote", witholding their complete ranking in order to eliminate the moderate Condorcet winner in the first round. But this critique strikes me as underwhelming for two reasons. First, it would be a high-variance tactical ploy. If your candidate ends up being eliminated instead, you forfeit a chance to influence the winner. And second, why not just prohibit bullet voting? Require complete or partial rankings in order for a ballot to be valid.

But, [independence of clones criterion](https://en.wikipedia.org/wiki/Independence_of_clones_criterion#Compliant_methods). That's why I can't support Borda. Candidates much more likely to be strategic than voters. AV fails strategic exit. Condorcet-Hare methods less likely to be susceptible to either strategic entry or exit. See [here](hybrids.pdf)