---
title: What's in your Anki?
author: Joseph T. Ornstein
date: '2020-08-08'
slug: anki
categories: 
- Personal
tags: []
images: []
draft: false
---

I have never been one to write margin notes or highlight books. To my Lawful Neutral brain, it just seems *wrong*, and also I get a lot of books from the library, where it is in fact wrong. But I also recognize that passive reading is a poor strategy for memory consolidation; too often I will read an entire book and be unable to recall more than a handful of details.

So my current system is to read with a blank deck of [Anki cards](https://ncase.me/remember/), creating a new card for everything I read that seems important enough to remember. This strategy has a few nice advantages:

1. Keeps my notes in one place, rather than spread out in margins across multiple books. 

2. Fosters some meta-cognitive awareness while reading, by requiring me to identify passages worth committing to memory.

3. Aids in memory consolidation by converting a passive learning exercise (reading) into an active learning exercise (recall with spaced repetition).

4. Helps form connections between ideas from different sources.

Spaced repetition has been one of my favorite new habits of 2020 -- which I suppose makes it clear how much time I've spent indoors this year. In addition to my "Things I Read" deck, I am also working through a deck of Spanish phrases.