---
title: What's in your Anki?
author: Joseph T. Ornstein
date: '2020-08-08'
slug: anki-contents
categories: 
- Personal
tags: []
images: []
draft: true
---

I have never been one to write margin notes or highlight books. I'm too Lawful Neutral and it just seems so wrong, especially for library books -- which constitute the majority of my reading consumption. But I also recognize that passive reading tends to inhibit memory consolidation; too often I will read an entire book and be unable to recall more than a handful of passages.

So my current system is to read with a blank deck of [Anki cards](), creating a new card for everything I read and want to remember. 

1. Keeps my notes in one place, rather than spread out in margin notes across multiple books. 

2. Fosters some meta-cognitive awareness while reading; requires me to identify passages that are worth remembering.

3. Helps form connections between ideas from different sources.

4. Aids in memory consolidation by converting a passive learning mode (reading) into an active learning mode (recall with spaced repetition).

Also people and Spanish.


