---
title: "Makefiles for Dummies who use Windows"
author: "Joseph T. Ornstein"
date: '2020-06-26'
slug: makefiles-dummies-windows
categories: 
 - R
 - Data Science
tags: []
images: []
---

```{R setup, include = FALSE}

```

Some combination of [Karl Broman's blog](https://kbroman.org/minimal_make/) and [Kieran Healy's book](https://plain-text.co/pull-it-together.html#pull-it-together) convinced me to try Makefiles as part of my workflow. Both authors have nice tutorials on the topic, but neither one appears to use Windows OS, so their instructions omit several hassles that such users must endure. Here is a dummified version of what I did to get everything working on my machine.

### Why Use Makefiles?

One benchmark for good reproducible research is the [Ten Year Challenge](https://rescience.github.io/ten-years/). Can you sucecssfully replicate a paper you wrote ten years ago? How hard did you make it for your future self? As far as I can tell, nothing I wrote in or around 2010 is reproducible without a bunch of reverse-engineering. Which is unfortunate, because at least some of that stuff may actually be good.

Starting in grad school I began to internalize the idea that every analysis should be captured in **code**. Anything accomplished through point-and-click is lost forever, and therefore not reproducible research. But even to this day, there are still some point-and-click components in my workflow. For example:

 - Open a project in RStudio and click "Run" to execute a script.
 - Download data from the Internet through a web browser.
 - Click "Build and View (F5)" in TeXStudio to rebuild a PDF.

This is all fairly innocuous stuff, but in ten years I will not be able to easily figure out (a) which R script I ran to create Figure 4, (b) where I got the raw data, (c) exactly what sequence of code I need to execute before I can build the PDF. By using a makefile, I can instead automate this whole process, and in so doing provide a nice self-documenting record of my entire workflow. 

<!-- Fully reproducible analysis replaces every point-and-click action with a script! Then you can just go back and read the script.  -->

**Advantages:**

1. It's automatic. One button (just type `make`) reproduces your entire workflow, even if you're using multiple languages (R, Python, TeX, shell scripting, etc).
2. It's fast. The `make` program only executes a line of code if something changed since the last time you ran it. If you just want to fiddle with the code that produces Figure 2, typing `make` won't rebuild your entire project, just the part you changed.
3. It's self-documenting. Anyone can open your Makefile in a text editor and see exactly what steps need to be taken, in what order, to generate your output.
4. Running analyses from the terminal is just inherently satisfying. This must be what real software developers feel like *all the time*.

So here is the set of steps I took to get it working on a Windows PC.


### Step 1: Download and setup GNU Make

Download [Make for Windows](http://gnuwin32.sourceforge.net/packages/make.htm). I used the [Setup Program](http://gnuwin32.sourceforge.net/downlinks/make.php) (that link should automatically start the download). Install it to a directory you will remember, like `C:\GnuWin32\`. 

Next, you need to add the `make.exe` directory to your PATH variable, so that Windows knows what to do when you type `make` into the Command Prompt. Here is a [step-by-step guide](https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/) to adding variables to PATH in Windows 10. If you installed Make in the same directory that I did, then the folder you will want to add is `C:\GnuWin32\bin\`.

The next time you open a new Command Prompt, you should be able to type `make` and not get a `'make' is not recognized as a command...` error. If not, go ahead and restart your computer. Or throw it into a river.

### Step 1a: Also add `R` to your PATH

In case you haven't already, add the directory that contains the `Rscript.exe` application to your PATH variable too. Now you can run R scripts from the command line.

### Step 2: Create a Makefile

For a more detailed tutorial on how to write Makefiles, see the links above. You can also play around with an example project I put together at [this repository](https://github.com/joeornstein/makefile-tutorial). It contains a LaTeX file, a folder with raw data, and some R scripts to clean the data, build tables, and build figures. The Makefile that stitches everything together looks like this:

```
# Define the list of tables
TABLES = tables/table1.tex tables/table2.tex

# Compile the paper
paper/paper.pdf : paper/paper.tex figures/fig1.png $(TABLES)
	pdflatex paper/paper.tex -output-directory paper

# Create Figure 1
figures/fig1.png : R/fig1.R data/clean_data.RDS
	Rscript R/fig1.R

# Create Tables 1 and 2
$(TABLES) : R/tables.R data/clean_data.RDS
	Rscript R/tables.R

# Clean the data
data/clean_data.RDS : R/clean_data.R data/raw_data.csv
	Rscript R/clean_data.R
```

No extension. Just put it in the root directory of your project and call it "Makefile". It's plain text so any text editor can open it, including RStudio.

Note: In [Karl Broman's tutorial](https://kbroman.org/minimal_make/) he uses the `CD` command when jumping around to subdirectories. Trying to adapt his syntax yielded a bunch of errors for me, likely because I'm accustomed to using path names relative to my R Project (e.g. `figures/fig1.png` instead of `../figures/fig1.png`). So instead I just include the full relative path for every script I want to call (in this case, my code is in the `R/` folder, and my LaTeX file is the in the `paper/` folder). 

### Step 3: Type `make`

You can also type `ctrl+shift+B` in RStudio. If there is a Makefile in your project directory, it will recognize it and use it as instructions to build your output! Very slick.


## Further Reading

[Mike Bostock](https://bost.ocks.org/mike/make/)  
[Karl Broman's Tutorial on Reproducible Research](https://kbroman.org/steps2rr/)
