---
title: "Dot Density Animation"
author: "Joseph T. Ornstein"
date: '2020-07-08'
slug: dot-density-animation
categories: 
 - R
 - Epidemiology
tags: []
images: []
draft: true
---

In a [previous post](../covid-animation/), I demonstrated some features of the `gganimate` package by animating a map of US COVID-19 cases. In this post, I'll make it a bit prettier.

```{r setup, echo = FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(sf)
library(readxl)
knitr::opts_chunk$set(warning=FALSE, message = FALSE)
```


```{r get tigris}

continental_states <- unique(tigris::fips_codes$state)[c(1, 3:11, 13:51)]

county_shp <- tigris::counties(state = continental_states,
                               cb = TRUE,
                               class = 'sf',
                               progress_bar = FALSE) %>% 
  mutate(fips = paste0(STATEFP, COUNTYFP)) %>% 
  select(fips)

countypops <- read_excel('../covid-animation/data/census/countypop.xlsx') %>% 
  mutate(fips = substr(id, 10, 14))


county_shp <- left_join(county_shp, countypops, by = 'fips')

# # 1 point represents 10,000 people
# points <- county_shp %>% 
#   st_sample(size = floor(county_shp$population / 10000)) %>% 
#   suppressWarnings
# 
# state_boundaries <- tigris::states(class = 'sf', cb = TRUE, progress_bar = FALSE) %>%
#   filter(STUSPS %in% continental_states)
# 
# ggplot() + 
#   geom_sf(data = state_boundaries) + 
#   geom_sf(data = points, size = 0.05) + 
#   theme_void()

```



## Further Reading

- [Dot Density Plots](https://tarakc02.github.io/dot-density/)