---
title: "Spaced Repetition for Syllabi"
author: "Joseph T. Ornstein"
date: '2020-06-05'
slug: spaced-repetition-for-syllabi
categories: 
 - Education
tags: []
images: []
---

```{R setup, include = FALSE}
library(tidyverse)
library(readxl)
```

We tell students that cramming the night before the test is a poor strategy. But of course it isn't. Students don't get good grades for effective long-term memory consolidation. They get good grades for scoring well on the exam *tomorrow*. If instructors want to encourage long-term memory building, they need to incentivize it.

For fun and a pretty graph, I replicated a version of the [Ebbinghaus experiment](https://en.wikipedia.org/wiki/Hermann_Ebbinghaus) on forgetting. I started with a list of 100 randomly generated license plate numbers and attempted to memorize them all.^[Can you remember your license plate number? You should!] To faithfully simulate cramming before the exam, I studied the list for about two hours the night before the first test, with frequent distraction from video games and small children. Here's how I fared on subsequent tests:

```{r plot forgetting curve, echo=F, message=FALSE, warning=FALSE}
master <- read_csv('data/master.csv')

test1 <- read_xlsx('data/test1.xlsx')
test2 <- read_xlsx('data/test2.xlsx')
test3 <- read_xlsx('data/test3.xlsx')
test4 <- read_xlsx('data/test4.xlsx')
test5 <- read_xlsx('data/test5.xlsx')

results <- tibble(day = c(1,2,4,10, 17),
                  correct = NA)

results$correct[1] <- sum(test1$license_plates %in% master$license_plates)
results$correct[2] <- sum(test2$license_plates %in% master$license_plates)
results$correct[3] <- sum(test3$license_plates %in% master$license_plates)
results$correct[4] <- sum(test4$license_plates %in% master$license_plates)
results$correct[5] <- sum(test5$license_plates %in% master$license_plates)

p <- ggplot(results, 
       aes(x=day, y=correct)) + 
  geom_point() + 
  geom_line() + 
  theme_bw() +
  xlab('Day') + ylab('Correct') +
  scale_y_continuous(breaks = function(x) seq(ceiling(x[1]), floor(x[2]), by = 1)) +
  scale_x_continuous(breaks = function(x) seq(ceiling(x[1]), floor(x[2]), by = 1))


p
```

The curve is not exactly exponential decay, but it's decay nonetheless. I remembered more than I would have expected on Day 1, and forgot about 30% of the license plates within a week. No doubt I would have lost more if not for the intermittent reinforcement of the tests themselves. And now I have about two dozen fake license plate numbers permanently taking up space in long-term memory. Great! 

If instead of cramming I had used something like [spaced repetition](https://www.gwern.net/Spaced-repetition), I'm sure I would have remembered many more license plates. See Nicky Case's fantastic [explorable explanation](https://ncase.me/remember/) for a guided tour to spaced repetition, but in a nutshell it works like this. Take a bunch of items you want to remember, and test yourself at varying intervals. If you successfully remember an item, increase the interval until the next test. If you fail, decrease the interval. That way you test the each item when you're most in danger of forgetting it. 

The two key elements of spaced repetition are (a) active recall rather than passive studying, and (b) spacing out study sessions. To design a course that leverages spaced repetition, consider the following ideas. 

#### Lots of low-stakes assessment

If a student only engages with a piece of content once during a lecture, then they haven't been set up to remember it. Anything you want a student to remember needs to be reinforced through active recall, ideally multiple times throughout the semester. Low-stakes vocabulary and reading comprehension quizzes seem so...primary school, but they have a place in higher education too. Any opportunity for active recall is an opportunity to strengthen memory.

#### The most important content goes first

<!-- For courses that lack an **explicit ladder structure**, there is rarely a clear guide for what order to present material. General to specific? Chronological?  -->

Putting new content during the final weeks of the semester is like a [Friday news dump](https://politicaldictionary.com/words/friday-news-dump/). Without much opportunity to practice and apply it, there's far less chance students will remember it. Instead, make sure that the content you most want students to remember goes near the beginning of the course, and save those last few weeks for review and applications.

#### Less content, more review

This may be a controversial one, but I would rather cover less content and have it be successfully rememebered than cover more content and have it crowd out the important stuff. Seriously consider what you want your students to get out of the course. Anything that is a Learning Objective with a capital-L should be reinforced multiple times. Prune other things to make room. Take time in class to review graded homework assignments, so they're not immediately forgotten after they're turned in. Create specific class periods for review of previously discussed material. Require your students to ask clarifying questions on a discussion board, and set aside time to review those questions. It all helps.

#### Decluster assignments

Rather than partitioning your assignments into tidy modules that move from one topic to the next, consider constructing assignments that reach back earlier in the course to test concepts you've already covered. My AP European History teacher called this a "RIPPLE & CONNECT", then she flapped her arms like an eagle and screeched. 

You don't have to do that last part. 

<!-- ## Isn't Rote Memorization Bad? -->

<!-- One objection to all of this .... But [Mnemosyne was the mother of the Muses](https://ncase.me/remember/). You can't have inspiration without memory. If you're a successful creative person, chances are that your creativity is built upon a bunch of existing knowledge about your field. Smart people tend to know a bunch of things. -->

## Further Reading

- [Nicky Case](https://ncase.me/remember/) has a fantastic explorable explanation of spaced repetition
- [Gwern](https://www.gwern.net/Spaced-repetition) has researched everything else you could possibly want to know
- [The Five Minute University](https://www.youtube.com/watch?v=kO8x8eoU3L4)

{{% youtube dZ6qMrVEdHY %}}



